
language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "master-coder-ll"

script:
  - mvn clean install -Dmaven.test.skip=true org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=master-coder-ll_v2ray-web-manager -Dsonar.login=${SONAR_TOKEN}
# - "mvn cobertura:cobertura"
#
after_success:
  - bash <(curl -s https://codecov.io/bash)